### ISSUE TITLE
Add Primitive Areas to Wilderness & primitive layer

### ISSUE THREAD

**Issue by BGranberg** [agrc/locate#160]
Add the BLM primitive areas (Dark Canyon and Grand Gulch...maybe others) query Landown to see how they are coded.

**Comment by stdavis** [comment]
@BGranberg I set the def query to be
```sql
DESIG IN ('Wilderness', 'National Monument') AND ADMIN IN ('BLM', 'USFS')
```

Take a look at production and let me know if that works...
