### ISSUE TITLE
Customer Feedback

### ISSUE THREAD

**Issue by steveoh** [agrc/locate#164]
> I would be looking for things like elem/mid/high school boundaries, local community centers/parks, even the cost of gas, etc as well if I were moving myself or a family to Utah

**Comment by stdavis** [comment]
Closing as stale unless @nathankota wants to ask the client about these suggestions.

**Comment by nathankota** [comment]
Focus is shifting to mapping and analysis needs for the state's broadband grant program, so we will hold-off on enhancements to locate.
