### ISSUE TITLE
sUre siTes text color

### ISSUE THREAD

**Issue by nathankota** [agrc/locate#172]
On the Sure Sites data layer category, change the color of "U" and "T" from blue to yellow or white. Client thinks blue is hard to read. I have doubts about yellow, but hard to tell until we can see it on the test site.

**Comment by steveoh** [comment]
that image is an svg. If you added classes to it, you could use css to style it.

**Comment by nathankota** [comment]
Should this change appear on test or prod? I don't see it on either.

**Comment by stdavis** [comment]
Here it is in production:
![image](https://user-images.githubusercontent.com/1326248/45032163-434dc100-b00e-11e8-8e33-4836fe5e3ecc.png)
It may be a caching issue for you. Try it in a different browser. Or maybe I updated the wrong logo?

**Comment by nathankota** [comment]
Yes, caching issue on my part. Sorry about that.
