### ISSUE TITLE
https

### ISSUE THREAD

**Issue by steveoh** [agrc/locate#173]
when I navigate to https://locate.utah.gov/ it times out.

![image](https://user-images.githubusercontent.com/325813/44155189-ddb3bf6a-a069-11e8-90b7-144ea9549427.png)

Was SSL not set up on this dns?

**Comment by stdavis** [comment]
I thought that it was. It's working this morning. Did you fix it?

**Comment by steveoh** [comment]
I did not fix it. I think the issue might be outside of the state network only then?

**Comment by stdavis** [comment]
INC0885392

**Comment by stdavis** [comment]
Trigger-happy!

**Comment by stdavis** [comment]
This is fixed now. Here's the update from networking:
>We are testing out a new tool that is automating our firewalls. Looks like it didn't write a rule on the outside interface which I corrected. Sorry about that.
