### ISSUE TITLE
Questar Gas now Dominion Energy

### ISSUE THREAD

**Issue by nathankota** [agrc/locate#182]
Change data so that Utilities section of the report shows Dominion Energy www.dominionenergy.com rather than Questar Gas www.questargas.com

![image](https://user-images.githubusercontent.com/15659642/65918082-0f220c80-e396-11e9-8784-4b609f024a96.png)

**Comment by stdavis** [comment]
@ZachBeck I think that this is a data update. Would you mind updating the data in `NaturalGasService_Approx` in SGID?

**Comment by ZachBeck** [comment]
I'll look into it. I think it's more involved than hitting up Dominion for an update. Looking at the metadata, someone in the office (Bert I'm guessing) was working with the Division of Public Utilities to create it.

**Comment by nathankota** [comment]
I'm also curious about the source of the data, if you're able to find that @ZachBeck. GOED is interested in other locate data updates.

**Comment by ZachBeck** [comment]
it's updated now

**Comment by stdavis** [comment]
Thanks, @ZachBeck. 

@nathankota The source is `SGID10.UTILITIES.NaturalGasService_Approx`. It should be updated in the app tomorrow assuming forky behaves well.

**Comment by stdavis** [comment]
![image](https://user-images.githubusercontent.com/1326248/67338087-9a9a4380-f4e5-11e9-9d1b-6df513c5a6d1.png)

**Comment by nathankota** [comment]
The other utility provider links work, but the dominion energy link goes to locate.utah.gov/www.dominionenergy.com

![image](https://user-images.githubusercontent.com/15659642/67396772-68c8c180-f565-11e9-911a-0449b14e38c4.png)

**Comment by stdavis** [comment]
@ZachBeck What's the value in the data for the link field for dominion energy? Maybe you are missing the `https://`?
