### ISSUE TITLE
Summary Report Not Working

### ISSUE THREAD

**Issue by nathankota** [agrc/locate#192]
Summary from Rebecca:

> I'm getting an error when generating a report anywhere I click on the locate.utah.gov map

I also tried to generate some reports and only get:

![image](https://user-images.githubusercontent.com/15659642/70945235-faa6f500-2011-11ea-9579-1eba5e37cebe.png)

**Comment by stdavis** [comment]
I missed a config update on the servers with this layer name. I believe that I have it fixed now.
