### ISSUE TITLE
Change All West Contact

### ISSUE THREAD

**Issue by nathankota** [agrc/locate#198]
Change contact info for All West Communications in bbecon database:
**From**
Bridget Watkins
Bridget.watkins@allwest.com

**To**
Jenny Prescott
Jenny.prescott@allwest.com

The phone number stays the same. 

![image](https://user-images.githubusercontent.com/15659642/88800074-caf1cb00-d164-11ea-9011-49b01302509b.png)

**Comment by stdavis** [comment]
This data is not in `bbecon.gdb`, it's in `UBBMAP.UBBADMIN.BB_Providers_Table` which I don't believe that I have a connection with edit privileges to. Once the data is edited there, it should flow to locate.utah.gov.

**Comment by nathankota** [comment]
Thank you for the clarification. @jacobdadams have you come across the `BB_Providers_Table`, or do we need to wait for @ZachBeck to return?

**Comment by stdavis** [comment]
It's in the broadband SDE database (UBBMAP)...

**Comment by jacobdadams** [comment]
I think I've got access, let me check.

**Comment by jacobdadams** [comment]
Ok, I've changed it in BB_Providers_Table but I'm still seeing Bridget Watkins when I generate a report. Does locate pull straight from the SDE, or does it ETL the data into local storage, and thus we need to wait for the next ETL?

**Comment by steveoh** [comment]
🚜

**Comment by stdavis** [comment]
https://github.com/agrc/locate/blob/675fe46ae5c358d961fd5933ce925043c7d860b1/scripts/locate_pallet.py#L76-L78

**Comment by nathankota** [comment]
/remind me to check locate summary report for update and close this on July 30

**Comment by jacobdadams** [comment]
It looks like it's still serving out the old info after the latest ship/lift even though the SDE has the new info. I've tested in incognito, so it's not a local cache issue. Is there something in the ship stage that it's missing?

**Comment by steveoh** [comment]
It has not shipped yet. The change must have missed yesterdays lift, so it will ship tonight.

**Comment by steveoh** [comment]
the data you are looking for is out there now?

**Comment by nathankota** [comment]
yes, all good now thanks

![image](https://user-images.githubusercontent.com/15659642/89199587-ff51f680-d56b-11ea-9aa6-bc8f5a90a879.png)
