### ISSUE TITLE
Remove SureSites

### ISSUE THREAD

**Issue by nathankota** [agrc/locate#204]
Remove all traces of Sure Sites from the locate app, including:

- [x] link to submit a Sure Site
- [x] Sure Sites layer on app
- [x] process to fetch/update sure site data/locations
- [x]  Sure sites database (or feature class?)

From Katherine M. at EDCUtah:

> We are no longer maintaining the site but are waiting to have our Site Ready Utah (mega sites and certified sites) website up and running before announcing we are shutting down Sure Sites. If you could remove all the Sure Site options from the map now that would be great. Thanks!

![image](https://user-images.githubusercontent.com/15659642/114876141-43fc8580-9dbb-11eb-80df-ab5cc812c374.png)

**Comment by stdavis** [comment]
We need to finish cleaning up the forklift pallet geocoding portion that is associated with these...
