### ISSUE TITLE
Footer Links are Broken

### ISSUE THREAD

**Issue by stdavis** [agrc/locate#205]
@nathankota In addition to the about and contact links, these links are also broken. They just go directly to utah.gov homepage. Would you like me to remove them or point them at something different?
![image](https://user-images.githubusercontent.com/1326248/115310241-b7d7be80-a12a-11eb-8752-d66b058d2186.png)

**Comment by nathankota** [comment]
I asked GOED about these too.

**Comment by nathankota** [comment]
@stdavis these links can be removed

**Comment by nathankota** [comment]
@stdavis - new feedback from GOED:

> Let's keep the one utah.gov on.  Do you know how the "Translate" tab might have worked?  Is it a Google app or something?

**Comment by stdavis** [comment]
> do you know how the "Translate" tab might have worked? Is it a Google app or something?

I don't know. I just know that it linked to https://utah.gov/translate.html which doesn't exist anymore.
