### ISSUE TITLE
Culinary Water layer not appearing

### ISSUE THREAD

**Issue by nathankota** [agrc/locate#206]
Utilities > Culinary Water layer does not appear on the map. Doesn't seem to be related to [this Porter issue](https://github.com/agrc/porter/issues/130), but the issue led me to test the layer in the locate app.

**Comment by nathankota** [comment]
Ha! I just saw the Slack convo about this, so I will close this issue. Apologies for the duplication.

**Comment by stdavis** [comment]
Just curious how you found out that they were not drawing. I have a feeling that this has been broken for a LONG time but maybe not.

**Comment by nathankota** [comment]
After seeing the Porter issue I went to the application and tried to turn on the layer, but it never rendered.
