### ISSUE TITLE
Culinary Water Service Areas layer not drawing

### ISSUE THREAD

**Issue by stdavis** [agrc/locate#207]
COLOR4 field is all nulls. Need to forklift and post process it back.

**Comment by stdavis** [comment]
@nathankota This should be fixed now in production: https://locate.utah.gov/#x=-12379128&y=4910989&scale=577791&l=11

**Comment by nathankota** [comment]
It's back! @stdavis I noticed the little info pop-out for the layer says _The location report provides the district name_, but there is no culinary water info on the report. Do you propose that we remove the verbiage from the pop-out, or add the provider name to the report? Let me know, and I'll create a new issue/task for it.

![image](https://user-images.githubusercontent.com/15659642/116093063-995e4f80-a663-11eb-986e-dbed31db5b14.png)

**Comment by stdavis** [comment]
I just forgot to update the path to the data in the report generation gp task. I'll fix it today. Thanks for the heads up!

**Comment by stdavis** [comment]
Actually, culinary water is not in the report at all. Not sure why. I feel like we should just remove the text from the popup but I'll add it to the report if you want me to.

**Comment by nathankota** [comment]
Remove text sounds like the best option.
