### ISSUE TITLE
Use new GOUtah logo

### ISSUE THREAD

**Issue by nathankota** [agrc/locate#214]
Replace the GOED logo with the new GOUtah logo in the left panel of the app. I have requested a dark GOUtah logo for the summary report and for the residential broadband site.

Old logo
![image](https://user-images.githubusercontent.com/15659642/144306886-dd9930d9-216b-40e9-9388-bc2e64fb5920.png)

New Logo
![Go_Utah_WHITE_Standard_290x59](https://user-images.githubusercontent.com/15659642/144306702-dbbdbc40-b626-4598-9ccc-2e67d4b4db59.png)

**Comment by stdavis** [comment]
@nathankota: This has been pushed to dev: https://locate.dev.utah.gov/

Please take a look and let me know if it can be pushed to prod.

**Comment by nathankota** [comment]
Looks like the "y" is getting cut off a bit. Any way to resolve that? The seal looks a little wonky too, but that must be the best it gets. Is it worth asking them for a different logo? If so, what are the best dimensions?

**Comment by steveoh** [comment]
> Is it worth asking them for a different logo?

A SVG graphic would be the best type, then the dimensions aren't important.

**Comment by stdavis** [comment]
![image](https://user-images.githubusercontent.com/1326248/144483260-a7f31ffb-dafb-48e0-9d4c-c9e8d98fc5ff.png)
Stupid windows scroll bars. It's already an SVG. I'll fix it...

**Comment by steveoh** [comment]
Ahh, windows scroll bars...

**Comment by stdavis** [comment]
OK, @nathankota, take another look: https://locate.dev.utah.gov/

**Comment by nathankota** [comment]
perfect!
