### ISSUE TITLE
Use new GOUtah logo on summary report

### ISSUE THREAD

**Issue by nathankota** [agrc/locate#215]
The dark logo can be found [here](https://drive.google.com/drive/folders/1hZotSAVRGy0Wed-73DUkLuR9jNVJd6On).

**Comment by stdavis** [comment]
@nathankota: This has been pushed to dev: https://locate.dev.utah.gov/

Please take a look and let me know if it can be pushed to prod.

**Comment by nathankota** [comment]
Ready for prod
