### ISSUE TITLE
2022 Enterprise Zones

### ISSUE THREAD

**Issue by nathankota** [agrc/locate#276]
Once @ZachBeck updates the 2022 zones data set based on info provided by James at GOEO, the 2022 boundaries will need to be added as a drop down selection on the app, and the 2018 data removed. 

![image](https://user-images.githubusercontent.com/15659642/214093405-b99e7905-724d-4a0b-b421-60ce4268b3fe.png)

**Comment by ZachBeck** [comment]
@stdavis the query `EXPYR IN ('2022', '2023', '2024')` should take care of the 2022 zones drop down. If it can be published to https://locate.dev.utah.gov/ for GOEO review that would be great.

**Comment by stdavis** [comment]
@ZachBeck I'm guessing the current def queries for these older years that I've received from you aren't appropriate anymore? Can you give me new queries for them?

2021 - `EXPYR NOT IN ('2018', '2019', '2020')`
2020 - `EXPYR NOT IN ('2018', '2019')`

**Comment by ZachBeck** [comment]
Those queries should still be fine since an EZ is active through a range of years but not after it expires. I think the 2019 static zones are probably ok but we'll want them to verify at some point.

**Comment by stdavis** [comment]
@ZachBeck https://locate.dev.utah.gov/ is ready for review by GOED.

**Comment by nathankota** [comment]
@stdavis GOEO is satisfied with the changes on dev. Please push to production when you get a chance.

![image](https://user-images.githubusercontent.com/15659642/217378580-cb8df363-d5f5-403f-97a7-430d97c4a9f0.png)
